### ISSUE TITLE
LaboAE : Objet Lot

### ISSUE THREAD

**Issue by d4e-ch** [d4e-digital-4-efficiency/lelaboae#2]
Salut Wissal,

C'est parti pour ce projet ;-)

On peut commencer par les Lots.

Conformément au document de specs :
```
Sélectionner l'entreprise ou le particulier
- Sélectionner le nom du diagnostiqueur si nécessaire (dans le cas des entreprises)
- Sélectionner le type d'analyse : amiante, VDI, PCB, PUF, HAP, poussière
- Degré d'urgence : normal, urgent, prioritaire
- Introduire une référence (client)
- Introduire un modèle de numérotation (à partir duquel se fait l'incrémentation des échantillons), comprenant un préfixe (par défaut « ECH-« ) et un nombre de chiffres (par défaut « 3 »). Le numéro de départ peut être modifié (« 1 » par défaut)
- Ajouter un nombre d'échantillons (si on génère les Echantillons à l’avance, sinon inutile)
- Enregistrer des échantillons sous forme de tableau à 2 colonne : Numéro généré à partir du modèle, modifiable | Description libre à saisir
NOTE : un numéro interne est attribué à chaque échantillon sous la forme YYMMXXXX
```

```
1.2.2 Récapitulatif
- Affichage des informations précédemment enregistrées (sans la description de tous les échantillons, juste un nombre d'échantillons)
- Pouvoir envoyer un mail de confirmation : texte standard + type d'analyse (d'amiante dans les matériaux, de VDI, de PCB dans les matériaux, de PCB dans l'air (PUF), de HAP dans les matériaux, de tampons de poussières) + référence externe + référence interne + délai d'analyse propre à chaque type de prestations ainsi qu'à chaque client (voir 1.1)
- Impression des étiquettes : incrémentation automatique au début de chaque mois, sur le modèle AAMMXXXX où AA=année en cours, MM=mois en cours, XXXX= depuis 0001
1.2.3 Editer un lot
- Pouvoir modifier toutes les entrées d'un lot
```

Pour information, voici leur logiciel actuel (qui ne correspond plus tout à fait à leur besoin) :
![image](https://user-images.githubusercontent.com/52782157/94562101-32132500-0265-11eb-9518-db893365bcb8.png)

A ta dispo si tu as des questions ;-)

Merci !

**Comment by Wissal-CampionTech** [comment]
Salut Alexandre,
J'ai crée la branche  "dev_lot" copie de master et j'ai ajouté un premier commit ( a327d59 )
Pour le moment il reste la fonctionnalité d'envoie du mail de confirmation que je suis en train de développer.
PS:  je ne trouve pas le projet sur Odoo.sh
Merci !

**Comment by Wissal-CampionTech** [comment]
Salut Alexandre, 
J'éspère que tu vas bien ,
j'ai ajouté un nouveau commit (349aad9) sur la branche dev_lot
Les éléments de texte du mail sont encore statique, on doit avancer dans la partie analyse pour pouvoir les rendre dynamiques.
Merci de tester la partie lot dévelopée
Bonne journée !

**Comment by d4e-ch** [comment]
Salut Wissal !

Je t'ai ajoutée dans OdooSH, désolé pour l'oubli !

Juste deux remarques :

- [ ] Le nom du lot doit être en lecture seule, et doit etre le numero interne du premier échantillon

![image](https://user-images.githubusercontent.com/52782157/95180517-5ff6ed00-07c2-11eb-9716-6d0d0cefa11a.png)


![image](https://user-images.githubusercontent.com/52782157/95180247-0262a080-07c2-11eb-9086-bfd1f379427e.png)

- [ ] Ces 4 champs devraient être remplis automatiquement.

Merci !

**Comment by d4e-ch** [comment]
> Salut Alexandre,
> J'éspère que tu vas bien ,
> j'ai ajouté un nouveau commit ([349aad9](https://github.com/d4e-digital-4-efficiency/lelaboae/commit/349aad924aff9afa450384c59932080f62c7539c)) sur la branche dev_lot
> Les éléments de texte du mail sont encore statique, on doit avancer dans la partie analyse pour pouvoir les rendre dynamiques.
> Merci de tester la partie lot dévelopée
> Bonne journée !

On s'est croisés, je vais retester ;-)

**Comment by Wissal-CampionTech** [comment]
Salut Alexandre,

C'est fait sur la branche dev_lot. Merci de tester,

Bonne journée !

**Comment by d4e-ch** [comment]
OK,  super comme ca !
Tu peux master + staging et passer à la suite ;-)
Merci!

**Comment by Wissal-CampionTech** [comment]
Alexandre,
C'est fait
